development:
 adapter: postgresql
 database: voluntary_development
 encoding: unicode
 pool: 5
 username: root
 password:

test: &TEST
 adapter: postgresql
 database: voluntary_test
 username: root
 password:
 encoding: unicode
 pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: voluntary_production
  encoding: utf8
  host: localhost
  pool: 5
  username: root
  password: 
  
cucumber:
 <<: *TEST